### ISSUE TITLE
Jenkins example and python package intake

### ISSUE THREAD

**Issue by kenvuejnj** [databricks/mlops-stacks#12]
Hello,

Thanks for creating this stack. I have two questions as below:

1. Is there an example with Jenkins as the CI/CD backend? 
2. If I already have a project as a python package, how can I add it to this stack?
3. Should we consider a python package structure instead of scripts inside this stack?

Thank you!

**Comment by smurching** [comment]
@kenvuejnj thanks for the questions!

1. Is there an example with Jenkins as the CI/CD backend?

No Jenkins backend support yet, although we'd welcome contributions to add it

2. If I already have a project as a python package, how can I add it to this stack?

Good question, I think it depends on the nature of your Python package. How do you currently implement model training with this package? If you can implement the interface required by CI/CD in the default stack (provide a notebook that trains and registers an ML model), then the stack (CI/CD, production training jobs, etc) should just work. Otherwise, some additional modifications may be needed

**Comment by arpitjasa-db** [comment]
Hi @kenvuejnj we've mostly moved away from Python and opted to use the in-house Databricks CLI where possible. We would still welcome Jenkins CI/CD contributions though!
